### ISSUE TITLE
Missing file : chemical_component_sets.pickle

### ISSUE THREAD

**Issue by amichon69** [SSchott/localalphafold3#1]
Bonjour/hello,

Thanks you for your script 

I think there is a missing step : the file chemical_component_sets.pickle is missing in : conda/envs/alphafold3/lib/python3.11/site-packages/alphafold3/constants/converters/chemical_component_sets.pickle

A friend send it to me from the docker file, maybe there is another way to do.

Alexis

**Comment by SSchott** [comment]
Right, you have to call `build_data` within the conda env. I added it now.

**Comment by SSchott** [comment]
wait, it was there. The file is under `alphafold3-conda/lib/python3.11/site-packages/alphafold3/constants/converters/chemical_component_sets.pickle` :thinking:
